source 'https://rubygems.org'

gem 'rails', '3.2.18'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'

gem 'coveralls', require: false
gem 'bcrypt', '3.1.7'

gem "paperclip", "~> 3.0"
gem "cocaine", "= 0.5.7" 


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'coffee-rails', '~> 3.2.1'
gem 'jquery-rails'
gem 'materialize-sass'
gem 'haml'
gem 'sprockets'
gem 'carrierwave'

group :test , :autotest do
  gem "minitest", "~> 4.0"
  gem 'shoulda-matchers'
  gem 'cucumber-rails', :require => false
  gem 'cucumber-rails-training-wheels'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  gem 'simplecov'
  gem 'ruby-prof'
end

# gem 'thin'
group :development, :test do
  gem "smart_listing"
  gem 'has_scope'
  gem 'rspec-rails'
  gem 'factory_girl'
  gem 'factory_girl_rails'
  gem 'fuubar'
end

group :development do
  gem 'webrick', '~> 1.3.1'
  gem 'quiet_assets'
end
# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
